import * as React from 'react';
import {
  ArrowLeft,
  ArrowUp,
  ArrowRight,
  ArrowDown,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  X,
  Check,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Maximize2,
  Minimize2,
  Moon,
  Sun,
  Bell,
  MessageSquare,
  Heart,
  Share2,
  RefreshCw,
  Filter,
  SortDesc,
  ShoppingBasket,
  Mail,
  Download,
  Image,
  Headphones,
  Music,
  Play,
  Star,
  TriangleAlert,
  Lock,
  Percent,
  Edit,
  Trash2,
  Search,
  Plus,
  Settings,
  User,
  Home,
  Eye,
  EyeOff,
  Copy,
  Save,
  Upload,
  FileDown,
  FolderOpen,
  File,
  AlertCircle,
  CheckCircle,
  XCircle,
  Clock,
  Calendar,
  Tag,
  Link2,
  Quote,
  Code,
  Terminal,
  Command,
  Palette,
  Layout,
  Grid3x3,
  List,
  Table,
  BarChart3,
  PieChart,
  LineChart,
  Globe,
  MapPin,
  Phone,
  QrCode,
  CreditCard,
  Wallet,
  Cpu,
  BatteryCharging,
  Wifi,
  Bluetooth,
  Camera,
  Mic,
  Volume2,
  VolumeX,
  Monitor,
  Smartphone,
  Laptop,
  Printer,
  MailOpen,
  Archive,
  Inbox,
  Box,
  Package,
  Truck,
  Shield,
  Key,
  LockKeyhole,
  LucideProps,
} from 'lucide-react';
import './Icon.css';

const iconMap = {
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-right': ArrowRight,
  'arrow-down': ArrowDown,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  x: X,
  check: Check,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  menu: Menu,
  maximize: Maximize2,
  minimize: Minimize2,
  moon: Moon,
  sun: Sun,
  bell: Bell,
  'message-square': MessageSquare,
  heart: Heart,
  share: Share2,
  refresh: RefreshCw,
  filter: Filter,
  'sort-desc': SortDesc,
  'shopping-basket': ShoppingBasket,
  mail: Mail,
  download: Download,
  image: Image,
  headphones: Headphones,
  music: Music,
  play: Play,
  star: Star,
  'triangle-alert': TriangleAlert,
  lock: Lock,
  percent: Percent,
  edit: Edit,
  delete: Trash2,
  search: Search,
  add: Plus,
  settings: Settings,
  user: User,
  home: Home,
  eye: Eye,
  'eye-off': EyeOff,
  copy: Copy,
  save: Save,
  upload: Upload,
  'file-down': FileDown,
  'folder-open': FolderOpen,
  file: File,
  error: XCircle,
  warning: AlertCircle,
  success: CheckCircle,
  clock: Clock,
  calendar: Calendar,
  tag: Tag,
  link: Link2,
  quote: Quote,
  code: Code,
  terminal: Terminal,
  command: Command,
  palette: Palette,
  layout: Layout,
  grid: Grid3x3,
  list: List,
  table: Table,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  globe: Globe,
  'map-pin': MapPin,
  phone: Phone,
  'qr-code': QrCode,
  'credit-card': CreditCard,
  wallet: Wallet,
  cpu: Cpu,
  'battery-charging': BatteryCharging,
  wifi: Wifi,
  bluetooth: Bluetooth,
  camera: Camera,
  mic: Mic,
  volume2: Volume2,
  'volume-x': VolumeX,
  monitor: Monitor,
  smartphone: Smartphone,
  laptop: Laptop,
  printer: Printer,
  'mail-open': MailOpen,
  archive: Archive,
  inbox: Inbox,
  box: Box,
  package: Package,
  truck: Truck,
  shield: Shield,
  key: Key,
  'lock-keyhole': LockKeyhole,
} as const;

export type IconName = keyof typeof iconMap;

export type IconSize = 'small' | 'medium';

export interface IconProps extends Omit<
  LucideProps,
  'size' | 'strokeWidth' | 'color'
> {
  name: IconName;
  size?: IconSize;
}

const Icon = React.forwardRef<SVGSVGElement, IconProps>(
  ({ name, size = 'medium', className = '', ...props }, ref) => {
    const LucideIcon = iconMap[name];

    if (!LucideIcon) {
      console.warn(`Icon "${name}" not found in iconMap`);
      return null;
    }

    const iconClasses = `icon icon--${size} ${className}`.trim();

    return <LucideIcon ref={ref} className={iconClasses} {...props} />;
  }
);

Icon.displayName = 'Icon';

export { Icon, iconMap };
